package model

import (
	"fmt"
	"net/netip"
	"sort"
	"strings"
)

// Record is a single DNS record managed by dns-sync. Forward records use
// Type "A"; reverse records use Type "PTR". Zone is the absolute DNS zone the
// record belongs to (trailing dot included).
type Record struct {
	Zone string
	Name string
	Type string
	Data string
	TTL  int
}

func (r Record) Key() string {
	return strings.Join([]string{r.Zone, r.Name, r.Type, r.Data}, "|")
}

type OpKind int

const (
	OpEnsureZone OpKind = iota + 1
	OpCreate
	OpDelete
)

func (k OpKind) String() string {
	switch k {
	case OpEnsureZone:
		return "ensure_zone"
	case OpCreate:
		return "create"
	case OpDelete:
		return "delete"
	}
	return "unknown"
}

type Op struct {
	Kind   OpKind
	Zone   string
	Record Record
}

// ForwardZoneFor returns the absolute parent zone of an FQDN by stripping the
// leftmost label. "host.sddc.lab" -> "sddc.lab.". Empty input returns "".
func ForwardZoneFor(fqdn string) string {
	fqdn = strings.TrimSuffix(fqdn, ".")
	i := strings.IndexByte(fqdn, '.')
	if i < 0 {
		return ""
	}
	return fqdn[i+1:] + "."
}

// ReverseZoneFor returns the /24-aligned in-addr.arpa zone for an IPv4 address.
// Per the lab's convention every PTR lives in a /24 reverse zone; IPv6 is not
// generated by this scaffold (see technitium-dns_design.md sec 7).
func ReverseZoneFor(addr netip.Addr) string {
	if !addr.Is4() {
		return ""
	}
	b := addr.As4()
	return fmt.Sprintf("%d.%d.%d.in-addr.arpa.", b[2], b[1], b[0])
}

// PTRNameFor returns the absolute PTR name for an IPv4 address.
func PTRNameFor(addr netip.Addr) string {
	if !addr.Is4() {
		return ""
	}
	b := addr.As4()
	return fmt.Sprintf("%d.%d.%d.%d.in-addr.arpa.", b[3], b[2], b[1], b[0])
}

// NormalizeFQDN returns an absolute, lower-cased FQDN with a single trailing dot.
// Empty input returns "".
func NormalizeFQDN(s string) string {
	s = strings.TrimSpace(strings.ToLower(s))
	if s == "" {
		return ""
	}
	if !strings.HasSuffix(s, ".") {
		s += "."
	}
	return s
}

// Zones returns the sorted, de-duplicated set of zones referenced by records.
func Zones(records []Record) []string {
	seen := map[string]struct{}{}
	for _, r := range records {
		if r.Zone != "" {
			seen[r.Zone] = struct{}{}
		}
	}
	out := make([]string, 0, len(seen))
	for z := range seen {
		out = append(out, z)
	}
	sort.Strings(out)
	return out
}
